import {
  Vacancy,
  NetworkingContact,
  SocialPost,
  CourseCatalogItem,
  ExternalCourseSuggestion,
} from "./types";

export const CATALOG_EXTRAS: CourseCatalogItem[] = [
  {
    id: "course_k8s_01",
    title: "Kubernetes en Producción",
    provider: "UTP",
    badge: "Avanzado",
    duration: "8 Semanas",
    pointsAwarded: 250,
    cost: "Gratis con UTP Account",
    url: "#",
    source: "internal",
    linkedGap: "Optimización avanzada en Kubernetes",
    description: "Despliegue de microservicios con HPA, Ingress y estrategias de rollout en entornos productivos.",
    image: "https://www.mercadonegro.pe/wp-content/uploads/2020/10/cursos-online-consejos-1.jpg",
    code: "44810",
    modality: "Virtual",
    speaker: "Ing. Patricia Vargas",
    modules: [
      {
        id: "k8s_m1",
        title: "Orquestación básica",
        lessons: [
          { id: "k8s_l1", title: "Pods, Deployments y Services", duration: "35 min" },
          { id: "k8s_l2", title: "ConfigMaps y Secrets", duration: "30 min" },
        ],
      },
    ],
  },
  {
    id: "course_itil_01",
    title: "Gestión de Servicios TI con ITIL",
    provider: "UTP",
    badge: "Certificación",
    duration: "6 Semanas",
    pointsAwarded: 200,
    cost: "Gratuito - Beca UTP+",
    url: "#",
    source: "internal",
    linkedGap: "Gestión de incidentes con ITIL 4",
    description: "Marco ITIL 4 para gestión de incidentes, cambios y mejora continua del servicio.",
    image: "https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?w=400&q=80",
    code: "44120",
    modality: "Híbrido",
    speaker: "Mg. Luis Herrera",
    modules: [
      {
        id: "itil_m1",
        title: "Fundamentos ITIL 4",
        lessons: [
          { id: "itil_l1", title: "Cadena de valor del servicio", duration: "25 min" },
          { id: "itil_l2", title: "Gestión de incidentes", duration: "30 min" },
        ],
      },
    ],
  },
  {
    id: "course_mkt_ga4",
    title: "Google Analytics 4 y Reportes Digitales",
    provider: "UTP",
    badge: "Certificación",
    duration: "6 Semanas",
    pointsAwarded: 200,
    cost: "Gratuito - Beca UTP+",
    url: "#",
    source: "internal",
    linkedGap: "Certificación Google Analytics 4",
    description: "Domina Google Analytics 4: configuración de propiedades, creación de informes personalizados y análisis de campañas de marketing digital.",
    image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=400&q=80",
    code: "44750",
    modality: "Virtual",
    speaker: "Mg. Luis Torres",
    modules: [
      {
        id: "ga4_m1",
        title: "Fundamentos GA4",
        lessons: [
          { id: "ga4_l1", title: "Configuración de propiedades en GA4", duration: "30 min" },
          { id: "ga4_l2", title: "Eventos y parámetros personalizados", duration: "35 min" },
        ],
      },
    ],
  },
  {
    id: "course_mkt_meta",
    title: "Meta Ads y Campañas Digitales",
    provider: "UTP",
    badge: "Especialización",
    duration: "8 Semanas",
    pointsAwarded: 250,
    cost: "100% de beca activa",
    url: "#",
    source: "internal",
    linkedGap: "Meta Ads y optimización de campañas",
    description: "Aprende a crear, optimizar y escalar campañas en Meta Ads con enfoque en métricas de rendimiento (CTR, CPA, ROAS).",
    image: "https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=400&q=80",
    code: "44760",
    modality: "Virtual",
    speaker: "Mg. Carla Mendoza",
    modules: [
      {
        id: "meta_m1",
        title: "Fundamentos Meta Ads",
        lessons: [
          { id: "meta_l1", title: "Configuración de campañas y públicos", duration: "30 min" },
          { id: "meta_l2", title: "Optimización de puja y presupuesto", duration: "35 min" },
        ],
      },
    ],
  },
  {
    id: "course_negotiation",
    title: "Negociación Internacional Estratégica",
    provider: "UTP",
    badge: "Avanzado",
    duration: "8 Semanas",
    pointsAwarded: 250,
    cost: "Gratis con UTP Account",
    url: "#",
    source: "internal",
    linkedGap: "Negociación intercultural",
    description: "Técnicas avanzadas de negociación internacional, manejo de conflictos interculturales y cierre de acuerdos comerciales con proveedores globales.",
    image: "https://www.mercadonegro.pe/wp-content/uploads/2020/10/cursos-online-consejos-1.jpg",
    code: "44910",
    modality: "Virtual",
    speaker: "Mg. Fernando Rivas",
    modules: [
      {
        id: "neg_m1", title: "Fundamentos de Negociación Global",
        lessons: [
          { id: "neg_l1", title: "Estilos de negociación intercultural", duration: "35 min" },
          { id: "neg_l2", title: "Preparación de una negociación internacional", duration: "30 min" },
        ],
      },
      {
        id: "neg_m2", title: "Técnicas y Cierre",
        lessons: [
          { id: "neg_l3", title: "Método Harvard de negociación", duration: "40 min" },
          { id: "neg_l4", title: "Cierre de acuerdos y contratos internacionales", duration: "35 min" },
        ],
      },
    ],
  },
  {
    id: "course_digital_trade",
    title: "Comercio Digital y E-Export",
    provider: "UTP",
    badge: "Certificación",
    duration: "6 Semanas",
    pointsAwarded: 200,
    cost: "Gratuito - Beca UTP+",
    url: "#",
    source: "internal",
    linkedGap: "Exportación digital",
    image: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=400&q=80",
    description: "Estrategias de comercio electrónico internacional, marketplaces globales y logística de exportación digital para PYMES peruanas.",
    code: "44920",
    modality: "Híbrido",
    speaker: "Lic. Andrea Salazar",
    modules: [
      {
        id: "dt_m1", title: "E-commerce Internacional",
        lessons: [
          { id: "dt_l1", title: "Marketplaces globales: Amazon, Alibaba, eBay", duration: "25 min" },
          { id: "dt_l2", title: "Logística de exportación digital", duration: "30 min" },
        ],
      },
    ],
  },
];

export const EXTERNAL_COURSE_SUGGESTIONS_STATIC: ExternalCourseSuggestion[] = [
  {
    id: "ext_udemy_git",
    platform: "Udemy",
    title: "Git y GitHub desde cero — Español",
    instructor: "Dev LATAM",
    price: "S/. 29.90",
    originalPrice: "S/. 149.90",
    rating: 4.7,
    students: "22,000+",
    linkedGap: "Git/GitHub y control de versiones",
    url: "https://www.udemy.com/course/git-github-es/",
    highlight: "Flujo colaborativo, branches y pull requests para tu primer proyecto backend.",
  },
  {
    id: "ext_meta_ads",
    platform: "Meta Blueprint",
    title: "Fundamentos de Publicidad en Meta",
    instructor: "Meta",
    price: "Gratis",
    rating: 4.6,
    students: "50,000+",
    linkedGap: "Meta Ads y optimización de campañas",
    url: "https://www.facebook.com/business/learn",
    highlight: "Certificación oficial para campañas en Facebook e Instagram.",
  },
  {
    id: "ext_ga4",
    platform: "Google Skillshop",
    title: "Google Analytics 4 — Certificación",
    instructor: "Google",
    price: "Gratis",
    rating: 4.8,
    students: "100,000+",
    linkedGap: "Certificación Google Analytics 4",
    url: "https://skillshop.withgoogle.com/",
    highlight: "Certificación GA4 exigida en vacantes de marketing digital junior.",
  },
  {
    id: "ext_udemy_comex",
    platform: "Udemy",
    title: "Comercio Exterior y Aduanas — Perú",
    instructor: "COMEX Academy",
    price: "S/. 39.90",
    originalPrice: "S/. 199.90",
    rating: 4.5,
    students: "8,400+",
    linkedGap: "Incoterms 2020 y normativa aduanera",
    url: "https://www.udemy.com/course/comex-peru/",
    highlight: "Incoterms, documentación de importación y despacho aduanero.",
  },
  {
    id: "ext_edx_supplychain",
    platform: "edX",
    title: "Supply Chain Management",
    instructor: "MIT — Massachusetts Institute of Technology",
    price: "Gratis (auditoría)",
    rating: 4.8,
    students: "180,000+",
    linkedGap: "Supply Chain Digital y ERP logístico",
    url: "https://www.edx.org/course/supply-chain-management",
    highlight: "Fundamentos de cadena de suministro, pronóstico de demanda y gestión de inventarios.",
  },
  {
    id: "ext_linkedin_logistics",
    platform: "LinkedIn Learning",
    title: "Logística 4.0: Transformación Digital",
    instructor: "Daniela Paz",
    price: "Gratis con UTP Account",
    rating: 4.6,
    students: "35,000+",
    linkedGap: "Supply Chain Digital y ERP logístico",
    url: "https://www.linkedin.com/learning/logistica-4-0",
    highlight: "Automatización logística, IoT en supply chain y ERP integrados.",
  },
  {
    id: "ext_coursera_negotiation",
    platform: "Coursera",
    title: "Negociación Internacional y Comercial",
    instructor: "Universidad de los Andes",
    price: "Gratis (auditoría)",
    originalPrice: "S/. 199",
    rating: 4.5,
    students: "65,000+",
    linkedGap: "Inglés comercial certificado (B2/C1)",
    url: "https://www.coursera.org/learn/negociacion-internacional",
    highlight: "Técnicas de negociación intercultural y cierre de acuerdos comerciales internacionales.",
  },
  {
    id: "ext_hubspot_email",
    platform: "HubSpot Academy",
    title: "Email Marketing y CRM",
    instructor: "HubSpot",
    price: "Gratis",
    rating: 4.7,
    students: "75,000+",
    linkedGap: "Email Marketing y CRM básico",
    url: "https://academy.hubspot.com/courses/email-marketing",
    highlight: "Funnels de email, automatización de campañas y gestión de contactos en CRM.",
  },
  {
    id: "ext_udemy_english",
    platform: "Udemy",
    title: "Inglés de Negocios para Comercio Exterior",
    instructor: "Business English Academy",
    price: "S/. 34.90",
    originalPrice: "S/. 179.90",
    rating: 4.6,
    students: "12,500+",
    linkedGap: "Inglés comercial certificado (B2/C1)",
    url: "https://www.udemy.com/course/ingles-negocios-comex/",
    highlight: "Vocabulario comercial, negociaciones en inglés y redacción de documentos internacionales.",
  },
  {
    id: "ext_coursera_export",
    platform: "Coursera",
    title: "Proceso de Exportación en Mercados Globales",
    instructor: "Universidad del Pacífico",
    price: "Gratis (auditoría)",
    originalPrice: "S/. 249",
    rating: 4.4,
    students: "28,000+",
    linkedGap: "Incoterms 2020 y normativa aduanera",
    url: "https://www.coursera.org/learn/exportacion-global",
    highlight: "Documentación de exportación, Incoterms, y negociación con compradores internacionales.",
  },
  {
    id: "ext_linkedin_leadership",
    platform: "LinkedIn Learning",
    title: "Liderazgo en Entornos Internacionales",
    instructor: "Dr. Ricardo Cuenca",
    price: "Gratis con UTP Account",
    rating: 4.5,
    students: "18,000+",
    linkedGap: "Metodologías Ágiles (Scrum)",
    url: "https://www.linkedin.com/learning/liderazgo-internacional",
    highlight: "Liderazgo intercultural, gestión de equipos globales y comunicación asertiva en entornos diversos.",
  },
];

export const INITIAL_VACANCIES_STATIC: Vacancy[] = [
  {
    id: "vac_backend_jr",
    company: "Globant",
    role: "Backend Developer Trainee",
    location: "Lima · Híbrido",
    salary: "S/. 1,800 - 2,200",
    matchScore: 72,
    description: "Buscamos estudiante de sistemas con bases en JavaScript/SQL y disposición para APIs REST y Git.",
    skillsRequired: ["JavaScript", "SQL", "Git/GitHub", "APIs REST"],
    skillsMissing: ["Docker", "Testing automatizado"],
    tipsForApplying: "Incluye un proyecto en GitHub y menciona tu interés en backend en el resumen del CV.",
  },
  {
    id: "vac_mkt_digital",
    company: "Rappi",
    role: "Asistente de Marketing Digital",
    location: "Lima · Presencial",
    salary: "S/. 1,500 - 1,900",
    matchScore: 78,
    description: "Apoya campañas de performance, reporting con GA4 y contenido para redes sociales.",
    skillsRequired: ["Google Analytics", "Meta Ads", "Canva", "SEO"],
    skillsMissing: ["Email Marketing", "CRM"],
    tipsForApplying: "Adjunta un portafolio con un caso de campaña y métricas de alcance o engagement.",
  },
  {
    id: "vac_comex",
    company: "Importaciones del Pacífico",
    role: "Asistente de Comercio Exterior",
    location: "Callao · Presencial",
    salary: "S/. 2,000 - 2,600",
    matchScore: 85,
    description: "Gestión documental de importaciones, coordinación con agentes de aduana y seguimiento logístico.",
    skillsRequired: ["Gestión Aduanera", "Excel Financiero", "Inglés Comercial", "Logística"],
    skillsMissing: ["SAP/ERP", "Inglés C1 certificado"],
    tipsForApplying: "Destaca métricas de contenedores gestionados y certificación PSM I si la tienes.",
  },
  {
    id: "vac_data_jr",
    company: "Interbank",
    role: "Analista de Datos Junior",
    location: "Lima · Híbrido",
    salary: "S/. 2,200 - 2,800",
    matchScore: 65,
    description: "Análisis de datos con SQL y reporting para equipos de producto digital.",
    skillsRequired: ["SQL", "Excel", "Power BI", "Python básico"],
    skillsMissing: ["ETL", "Cloud"],
    tipsForApplying: "Menciona proyectos académicos con consultas SQL y visualización de datos.",
  },
  {
    id: "vac_intel_comercial",
    company: "Cámara de Comercio de Lima",
    role: "Analista de Inteligencia Comercial",
    location: "Lima · Presencial",
    salary: "S/. 2,000 - 2,500",
    matchScore: 82,
    description: "Investigación de mercados internacionales, análisis de indicadores de comercio exterior y elaboración de reportes sectoriales.",
    skillsRequired: ["Excel Financiero", "Análisis de Datos", "Inglés Comercial", "Logística Internacional"],
    skillsMissing: ["Power BI", "METRC/Estadística"],
    tipsForApplying: "Destaca tu experiencia con análisis de datos y manejo de indicadores de comercio exterior.",
  },
  {
    id: "vac_supply_chain",
    company: "Ripley Corp",
    role: "Supply Chain Trainee",
    location: "Lima · Híbrido",
    salary: "S/. 1,800 - 2,300",
    matchScore: 78,
    description: "Apoyo en la planificación de la cadena de suministro, coordinación con proveedores y seguimiento de inventarios.",
    skillsRequired: ["Logística", "Excel Financiero", "Negociación", "Inglés Comercial"],
    skillsMissing: ["SAP ERP", "Power BI", "Pronóstico de demanda"],
    tipsForApplying: "Menciona tu experiencia en logística internacional y manejo de inventarios.",
  },
  {
    id: "vac_logistics",
    company: "DHL Global Forwarding",
    role: "Asistente de Logística Internacional",
    location: "Callao · Presencial",
    salary: "S/. 2,200 - 2,800",
    matchScore: 88,
    description: "Coordinación de operaciones de importación y exportación, gestión documental y seguimiento de envíos internacionales.",
    skillsRequired: ["Logística Internacional", "Gestión Aduanera", "Inglés Comercial", "Negociación"],
    skillsMissing: ["SAP/ERP Logístico", "Incoterms 2020"],
    tipsForApplying: "Resalta tu conocimiento en procesos aduaneros y tu certificación PSM I si la tienes.",
  },
  {
    id: "vac_export",
    company: "AgroPerú Export",
    role: "Analista de Exportaciones Junior",
    location: "Lima · Presencial",
    salary: "S/. 1,900 - 2,400",
    matchScore: 80,
    description: "Gestión de procesos de exportación, documentación internacional y coordinación con agentes de aduana y navieras.",
    skillsRequired: ["Gestión Aduanera", "Excel Financiero", "Inglés Comercial", "Logística"],
    skillsMissing: ["Incoterms 2020", "SAP/ERP"],
    tipsForApplying: "Incluye ejemplos de proyectos de exportación y tu manejo de documentación internacional.",
  },
];

export const INITIAL_NETWORKING_CONTACTS_STATIC: NetworkingContact[] = [
  {
    id: "c_mentor_sys",
    name: "Ing. Carlos Mendoza",
    role: "Tech Lead Backend",
    company: "Globant",
    type: "mentor",
    isConnected: false,
    isPending: false,
    compatibilityText: "Alineado a Ingeniería de Sistemas y desarrollo backend.",
    bio: "Egresado UTP con 8 años en APIs REST y arquitecturas cloud. Mentor en ferias de empleo tech.",
  },
  {
    id: "c_rec_mkt",
    name: "Valeria Soto",
    role: "Talent Acquisition",
    company: "Rappi",
    type: "reclutador",
    isConnected: false,
    isPending: false,
    compatibilityText: "Reclutadora de marketing digital y growth.",
    bio: "Busca practicantes con portafolio digital y certificación GA4.",
  },
  {
    id: "c_alumni_comex",
    name: "Miguel Torres",
    role: "Especialista COMEX",
    company: "DHL Global Forwarding",
    type: "alumni",
    isConnected: true,
    isPending: false,
    compatibilityText: "Egresado UTP — Negocios Internacionales.",
    bio: "8 años en logística internacional y gestión aduanera. Abierto a mentorías.",
  },
  {
    id: "c_rec_tech",
    name: "Ana Ruiz",
    role: "HR Business Partner",
    company: "BCP",
    type: "reclutador",
    isConnected: false,
    isPending: true,
    compatibilityText: "Vacantes tech y analítica para recién egresados.",
    bio: "Coordina procesos de selección para trainees y analistas junior.",
  },
  {
    id: "c_alumni_supply",
    name: "Carlos Gutiérrez",
    role: "Supply Chain Manager",
    company: "Alicorp",
    type: "alumni",
    isConnected: false,
    isPending: false,
    compatibilityText: "Egresado UTP — Negocios Internacionales. Líder en Supply Chain.",
    bio: "10+ años en gestión de cadena de suministro en Alicorp. Director de la red de egresados UTP de Negocios Internacionales.",
  },
  {
    id: "c_rec_logistics",
    name: "Mariana López",
    role: "Talent Acquisition Logistics",
    company: "DHL Global Forwarding",
    type: "reclutador",
    isConnected: false,
    isPending: false,
    compatibilityText: "Reclutadora especializada en logística y comercio exterior.",
    bio: "Busca talento joven para operaciones logísticas internacionales. Valora certificaciones y experiencia práctica.",
  },
  {
    id: "c_mentor_comex",
    name: "Fernando Rivas",
    role: "Director de Comercio Exterior",
    company: "Cámara de Comercio de Lima",
    type: "mentor",
    isConnected: false,
    isPending: false,
    compatibilityText: "Mentor en comercio exterior y negociación internacional.",
    bio: "Más de 15 años liderando proyectos de internacionalización. Mentor UTP+ para estudiantes de Negocios Internacionales.",
  },
  {
    id: "c_alumni_export",
    name: "Lucía Fernández",
    role: "Jefa de Exportaciones",
    company: "AgroPerú Export",
    type: "alumni",
    isConnected: false,
    isPending: false,
    compatibilityText: "Egresada UTP — Negocios Internacionales. Experta en exportaciones.",
    bio: "Lidera el equipo de exportaciones de AgroPerú. Apasionada por el desarrollo del comercio exterior peruano.",
  },
];

export const INITIAL_COMMUNITY_POSTS_STATIC: SocialPost[] = [
  {
    id: "post_hackathon",
    authorName: "Comunidad UTP",
    authorCareer: "Empleabilidad",
    authorSemester: 0,
    avatarColor: "bg-[#B50E30]",
    content: "🚀 Inscripciones abiertas al Hackathon UTP & Xpedition 2026. Forma tu equipo y presenta un proyecto que demuestre tu stack.",
    date: "Hace 2 horas",
    likes: 45,
    likedByUser: false,
    category: "evento",
    comments: [],
  },
  {
    id: "post_git_tip",
    authorName: "Ing. Carlos Mendoza",
    authorCareer: "Ingeniería de Sistemas",
    authorSemester: 0,
    avatarColor: "bg-neutral-800",
    content: "Tip para primer empleo tech: un repo en GitHub con README claro vale más que 10 cursos sin proyecto. ¿Quién comparte el suyo?",
    date: "Hace 1 día",
    likes: 32,
    likedByUser: false,
    category: "ayuda",
    comments: [
      {
        authorName: "Adrian Q.",
        content: "¡Gracias! Estoy armando mi primera API REST para subirla esta semana.",
        date: "Hace 18 horas",
      },
    ],
  },
  {
    id: "post_mkt_case",
    authorName: "Camila R.",
    authorCareer: "Marketing",
    authorSemester: 6,
    avatarColor: "bg-purple-600",
    content: "Comparto mi caso de estudio de marketing digital para un emprendimiento local 📊 Estrategia de contenido + métricas de engagement.",
    date: "Hace 3 días",
    likes: 28,
    likedByUser: false,
    category: "proyecto",
    comments: [],
  },
  {
    id: "post_comex_networking",
    authorName: "Miguel Torres",
    authorCareer: "Negocios Internacionales",
    authorSemester: 10,
    avatarColor: "bg-[#B50E30]",
    content: "📢 Invitación a la red de egresados COMEX UTP. Este viernes organizamos un networking con profesionales de DHL, Alicorp y la Cámara de Comercio. ¡Inscríbete!",
    date: "Hace 6 horas",
    likes: 38,
    likedByUser: false,
    category: "evento",
    comments: [
      {
        authorName: "Jose Sandoval",
        content: "¡Me apunto! Justo estoy buscando conectar con profesionales del sector.",
        date: "Hace 4 horas",
      },
    ],
  },
  {
    id: "post_logistics_logro",
    authorName: "Carlos Gutiérrez",
    authorCareer: "Negocios Internacionales",
    authorSemester: 0,
    avatarColor: "bg-black",
    content: "Comparto mi experiencia: la certificación en Supply Chain Digital me abrió puertas en Alicorp. Si estudian Negocios Internacionales, no subestimen la parte digital de la logística 📦📊",
    date: "Hace 2 días",
    likes: 52,
    likedByUser: false,
    category: "logro",
    comments: [],
  },
];
