import {
  Vacancy,
  NetworkingContact,
  SocialPost,
  CourseCatalogItem,
  ExternalCourseSuggestion,
} from "./types";

export const CATALOG_EXTRAS: CourseCatalogItem[] = [
  {
    id: "course_k8s_01",
    title: "Kubernetes en Producción",
    provider: "UTP",
    badge: "Avanzado",
    duration: "8 Semanas",
    pointsAwarded: 250,
    cost: "Gratis con UTP Account",
    url: "#",
    source: "internal",
    linkedGap: "Optimización avanzada en Kubernetes",
    description: "Despliegue de microservicios con HPA, Ingress y estrategias de rollout en entornos productivos.",
    image: "https://www.mercadonegro.pe/wp-content/uploads/2020/10/cursos-online-consejos-1.jpg",
    code: "44810",
    modality: "Virtual",
    speaker: "Ing. Patricia Vargas",
    modules: [
      {
        id: "k8s_m1",
        title: "Orquestación básica",
        lessons: [
          { id: "k8s_l1", title: "Pods, Deployments y Services", duration: "35 min" },
          { id: "k8s_l2", title: "ConfigMaps y Secrets", duration: "30 min" },
        ],
      },
    ],
  },
  {
    id: "course_itil_01",
    title: "Gestión de Servicios TI con ITIL",
    provider: "UTP",
    badge: "Certificación",
    duration: "6 Semanas",
    pointsAwarded: 200,
    cost: "Gratuito - Beca UTP+",
    url: "#",
    source: "internal",
    linkedGap: "Gestión de incidentes con ITIL 4",
    description: "Marco ITIL 4 para gestión de incidentes, cambios y mejora continua del servicio.",
    code: "44120",
    modality: "Híbrido",
    speaker: "Mg. Luis Herrera",
    modules: [
      {
        id: "itil_m1",
        title: "Fundamentos ITIL 4",
        lessons: [
          { id: "itil_l1", title: "Cadena de valor del servicio", duration: "25 min" },
          { id: "itil_l2", title: "Gestión de incidentes", duration: "30 min" },
        ],
      },
    ],
  },
];

export const EXTERNAL_COURSE_SUGGESTIONS_STATIC: ExternalCourseSuggestion[] = [
  {
    id: "ext_udemy_git",
    platform: "Udemy",
    title: "Git y GitHub desde cero — Español",
    instructor: "Dev LATAM",
    price: "S/. 29.90",
    originalPrice: "S/. 149.90",
    rating: 4.7,
    students: "22,000+",
    linkedGap: "Git/GitHub y control de versiones",
    url: "https://www.udemy.com/course/git-github-es/",
    highlight: "Flujo colaborativo, branches y pull requests para tu primer proyecto backend.",
  },
  {
    id: "ext_meta_ads",
    platform: "Meta Blueprint",
    title: "Fundamentos de Publicidad en Meta",
    instructor: "Meta",
    price: "Gratis",
    rating: 4.6,
    students: "50,000+",
    linkedGap: "Meta Ads y optimización de campañas",
    url: "https://www.facebook.com/business/learn",
    highlight: "Certificación oficial para campañas en Facebook e Instagram.",
  },
  {
    id: "ext_ga4",
    platform: "Google Skillshop",
    title: "Google Analytics 4 — Certificación",
    instructor: "Google",
    price: "Gratis",
    rating: 4.8,
    students: "100,000+",
    linkedGap: "Certificación Google Analytics 4",
    url: "https://skillshop.withgoogle.com/",
    highlight: "Certificación GA4 exigida en vacantes de marketing digital junior.",
  },
  {
    id: "ext_udemy_comex",
    platform: "Udemy",
    title: "Comercio Exterior y Aduanas — Perú",
    instructor: "COMEX Academy",
    price: "S/. 39.90",
    originalPrice: "S/. 199.90",
    rating: 4.5,
    students: "8,400+",
    linkedGap: "Incoterms 2020 y normativa aduanera",
    url: "https://www.udemy.com/course/comex-peru/",
    highlight: "Incoterms, documentación de importación y despacho aduanero.",
  },
];

export const INITIAL_VACANCIES_STATIC: Vacancy[] = [
  {
    id: "vac_backend_jr",
    company: "Globant",
    role: "Backend Developer Trainee",
    location: "Lima · Híbrido",
    salary: "S/. 1,800 - 2,200",
    matchScore: 72,
    description: "Buscamos estudiante de sistemas con bases en JavaScript/SQL y disposición para APIs REST y Git.",
    skillsRequired: ["JavaScript", "SQL", "Git/GitHub", "APIs REST"],
    skillsMissing: ["Docker", "Testing automatizado"],
    tipsForApplying: "Incluye un proyecto en GitHub y menciona tu interés en backend en el resumen del CV.",
  },
  {
    id: "vac_mkt_digital",
    company: "Rappi",
    role: "Asistente de Marketing Digital",
    location: "Lima · Presencial",
    salary: "S/. 1,500 - 1,900",
    matchScore: 78,
    description: "Apoya campañas de performance, reporting con GA4 y contenido para redes sociales.",
    skillsRequired: ["Google Analytics", "Meta Ads", "Canva", "SEO"],
    skillsMissing: ["Email Marketing", "CRM"],
    tipsForApplying: "Adjunta un portafolio con un caso de campaña y métricas de alcance o engagement.",
  },
  {
    id: "vac_comex",
    company: "Importaciones del Pacífico",
    role: "Asistente de Comercio Exterior",
    location: "Callao · Presencial",
    salary: "S/. 2,000 - 2,600",
    matchScore: 85,
    description: "Gestión documental de importaciones, coordinación con agentes de aduana y seguimiento logístico.",
    skillsRequired: ["Gestión Aduanera", "Excel Financiero", "Inglés Comercial", "Logística"],
    skillsMissing: ["SAP/ERP", "Inglés C1 certificado"],
    tipsForApplying: "Destaca métricas de contenedores gestionados y certificación PSM I si la tienes.",
  },
  {
    id: "vac_data_jr",
    company: "Interbank",
    role: "Analista de Datos Junior",
    location: "Lima · Híbrido",
    salary: "S/. 2,200 - 2,800",
    matchScore: 65,
    description: "Análisis de datos con SQL y reporting para equipos de producto digital.",
    skillsRequired: ["SQL", "Excel", "Power BI", "Python básico"],
    skillsMissing: ["ETL", "Cloud"],
    tipsForApplying: "Menciona proyectos académicos con consultas SQL y visualización de datos.",
  },
];

export const INITIAL_NETWORKING_CONTACTS_STATIC: NetworkingContact[] = [
  {
    id: "c_mentor_sys",
    name: "Ing. Carlos Mendoza",
    role: "Tech Lead Backend",
    company: "Globant",
    type: "mentor",
    isConnected: false,
    isPending: false,
    compatibilityText: "Alineado a Ingeniería de Sistemas y desarrollo backend.",
    bio: "Egresado UTP con 8 años en APIs REST y arquitecturas cloud. Mentor en ferias de empleo tech.",
  },
  {
    id: "c_rec_mkt",
    name: "Valeria Soto",
    role: "Talent Acquisition",
    company: "Rappi",
    type: "reclutador",
    isConnected: false,
    isPending: false,
    compatibilityText: "Reclutadora de marketing digital y growth.",
    bio: "Busca practicantes con portafolio digital y certificación GA4.",
  },
  {
    id: "c_alumni_comex",
    name: "Miguel Torres",
    role: "Especialista COMEX",
    company: "DHL Global Forwarding",
    type: "alumni",
    isConnected: true,
    isPending: false,
    compatibilityText: "Egresado UTP — Negocios Internacionales.",
    bio: "8 años en logística internacional y gestión aduanera. Abierto a mentorías.",
  },
  {
    id: "c_rec_tech",
    name: "Ana Ruiz",
    role: "HR Business Partner",
    company: "BCP",
    type: "reclutador",
    isConnected: false,
    isPending: true,
    compatibilityText: "Vacantes tech y analítica para recién egresados.",
    bio: "Coordina procesos de selección para trainees y analistas junior.",
  },
];

export const INITIAL_COMMUNITY_POSTS_STATIC: SocialPost[] = [
  {
    id: "post_hackathon",
    authorName: "Comunidad UTP",
    authorCareer: "Empleabilidad",
    authorSemester: 0,
    avatarColor: "bg-[#B50E30]",
    content: "🚀 Inscripciones abiertas al Hackathon UTP & Xpedition 2026. Forma tu equipo y presenta un proyecto que demuestre tu stack.",
    date: "Hace 2 horas",
    likes: 45,
    likedByUser: false,
    category: "evento",
    comments: [],
  },
  {
    id: "post_git_tip",
    authorName: "Ing. Carlos Mendoza",
    authorCareer: "Ingeniería de Sistemas",
    authorSemester: 0,
    avatarColor: "bg-neutral-800",
    content: "Tip para primer empleo tech: un repo en GitHub con README claro vale más que 10 cursos sin proyecto. ¿Quién comparte el suyo?",
    date: "Hace 1 día",
    likes: 32,
    likedByUser: false,
    category: "ayuda",
    comments: [
      {
        authorName: "Adrian Q.",
        content: "¡Gracias! Estoy armando mi primera API REST para subirla esta semana.",
        date: "Hace 18 horas",
      },
    ],
  },
  {
    id: "post_mkt_case",
    authorName: "Camila R.",
    authorCareer: "Marketing",
    authorSemester: 6,
    avatarColor: "bg-purple-600",
    content: "Comparto mi caso de estudio de marketing digital para un emprendimiento local 📊 Estrategia de contenido + métricas de engagement.",
    date: "Hace 3 días",
    likes: 28,
    likedByUser: false,
    category: "proyecto",
    comments: [],
  },
];
